### ISSUE TITLE
Device Naming 

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-desktop#2]
## Device Naming
- User clicked on 'Get Started' 
- User is invited to name their device
- User cannot proceed to CoMapeo without naming their device
- User successfully names their device
- User lands on the Map screen

## Todo 

- [ ] Display screen as designed
- [ ] Make 'Add a Name for our device' mandatory field to be able to  `Add Name` 
- [ ] Do not display tooltip
- [ ] Create `Add Name` button
- [ ] Display device name as entered on first screen
- [ ] Create `Go to Map` button
- [ ] Display the map screen when clicking the `Done` button

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1069-4606&mode=design&t=7vnK6OIYo99rronU-0

## Copydeck
https://docs.google.com/spreadsheets/d/18x135fNGqwryXcBoJGvtNSJJMHuPB48Vp0o1l16UyzY/edit?usp=sharing
