### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-desktop#3]
## Settings
- Integrate a Settings button on the main menu
- Organize the menu 

## 1 Settings button
<img width="669" alt="Screen Shot 2023-11-29 at 12 13 46 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/c2716d25-9065-4178-9fc1-b733b2b186bf">

## Todo
- [ ] Display the `Settings` button as designed

## Todo
- [ ] Display the menu as designed for Settings
- [ ] Create a `Create or Join Project` button 
- [ ] Display `Create a new project or join existing one` under `Create or Join Project`  button 
- [ ] Create a `Project Settings` button
- [ ] Display `Categories, Config, Icons`  under `Project Settings` button
- [ ] Create a `App Settings` button
- [ ] Display `Language, Security, Coordinates` under  `App Settings`  button
- [ ] Create a `Experimental Feature` button
- [ ] Create a `About CoMapeo` button
- [ ] Display `LVersion and build number` under  `About CoMapeo`  button

## 3 Project Settings
<img width="658" alt="Screen Shot 2023-11-29 at 12 15 13 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/338354e5-6787-46da-bd37-7f028065d6be">

## Todo
- [ ] Display the menu as designed
- [ ] Create a `Device Name` button 
- [ ] Create a `Configuration` button 
- [ ] Create a `Your Team` button 

## 4 App Settings
<img width="666" alt="Screen Shot 2023-11-29 at 12 15 48 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/3f910099-e362-449a-b3ee-b67640660a2f">

## Todo
- [ ] Display the menu as designed 
- [ ] Create a `Language` button 
- [ ] Create a `Coordinate System` button 
- [ ] Create a `Map Management` button 
- [ ] Create a `Security` button 
- [ ] Create a `Experiments` button 

## 5 Map Management
<img width="668" alt="Screen Shot 2023-11-29 at 12 17 51 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/3f577e94-7c7a-42f9-9c1f-9c4f440fe58f">

## Todo
- [ ] Display the menu as designed 
- [ ] Create a `Directional arrow` button 
- [ ] Create a `Background maps` button 
- [ ] Create a `Data layers` button 

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1567-547&mode=design&t=pTdIgujzMShkwaNL-0
