### ISSUE TITLE
Leave Project

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-desktop#6]
## Leave Project
- User has joined a project and wishes to leave it
- User is on the *Your Team* screen and clicks on `Leave Project`
- If user is a Coordinator, and they are more than 1 coordinator in the project, follow the flow below
- If user is a Coordinator, and they are the only Coordinator go to 5

# 1 
<img width="319" alt="Screen Shot 2023-10-02 at 2 32 37 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/75c5c9d5-9c1f-4c64-9850-b0dda95ed7a1">

Use this design but edit content to match mobile
<img width="633" alt="Screen Shot 2023-11-29 at 12 26 14 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/3c7460e8-27e4-4a7d-bd54-62c28c1923f1">

## ToDo
- [ ] Display **Leave project**
- [ ] Display **This will remove all Project Name data from your device**
- [ ] Add mandatory checkbox next to **I understand I will be deleting all data from Project Name from my device**
- [ ] User cannot leave project is box is unchecked
- [ ] Create `Leave Project` button
- [ ] Create `Cancel` button

# 2 Error state
<img width="307" alt="Screen Shot 2023-10-02 at 2 35 51 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/9ae4e05d-0676-4df6-b91b-78bd5748150d">

## Todo
- [ ] If user tries to click on **Leave project** without checking the box, display error message

# 3 Leaving project progress
<img width="680" alt="Screen Shot 2023-10-02 at 6 25 33 PM" src="https://github.com/digidem/mapeo-mobile/assets/78557542/29422ed6-d90c-4c95-bab2-697ddd907ba2">

- [ ] Display progress bar as designed

# 4 Leaving project success

<img width="651" alt="Screen Shot 2023-11-29 at 12 28 42 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/abf2cd5a-0219-4f28-8a00-5a9cbfc534f7">

- [ ] Display **You have left Project Catapult**
- [ ] Create `Close` button

# 5 Leaving project/ 1 coordinator

<img width="251" alt="Screen Shot 2023-11-29 at 12 33 08 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/ce33f17a-4da8-4cc7-aae1-822e9347f736">

- [ ] Display copy as designed
- [ ] Create `Go back` button

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1099-856&mode=design&t=ypas7TLUlTe7pRjw-0

## Copydeck
https://docs.google.com/spreadsheets/d/1QXPIdnOFIRAk41hfnGBMw1zEafD8Vp1ZwqDm4XiUR3g/edit#gid=588765348
