### ISSUE TITLE
Join Project

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-desktop#7]
## Join Project
- User was in Settings./Your Team
- User clicked on Join a project

<img width="662" alt="Screen Shot 2023-11-29 at 12 37 37 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/3efed978-d45e-46e9-bbb6-431ec84284c8">

## Todo
- [ ] Display page
- [ ] Display text title **How to join a project**
- [ ] Display text explaining how to join a project, copy tbd, for now add  **To join a project find a Coordinator of the project you wish to join. Tell them your device name and the Coordinator will send you an invite.**
- [ ] Create `Close` button

## Design
https://docs.google.com/spreadsheets/d/1kpoU-mr-fJyxbAxERqrhC2IyRd3T64YEs8fUDzbAFQY/edit#gid=583501046

## Copydeck
https://docs.google.com/spreadsheets/d/1kpoU-mr-fJyxbAxERqrhC2IyRd3T64YEs8fUDzbAFQY/edit#gid=583501046
