### ISSUE TITLE
Device Invite

### ISSUE THREAD

**Issue by ximenabb** [digidem/comapeo-desktop#8]
## Your team
- User was on Settings/Project Settings and clicked on **Your team**
- User is on a project and can see the project and available devices, leave project
- If user tries leave project if they are the only coordinator ( if clicked - pop up warning)
- User clicks on **Invite **

# 1
<img width="653" alt="Screen Shot 2023-11-29 at 12 39 40 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/4ea960c3-22a9-4e0d-bd5b-d6662eea6c8d">

## Todo
- [ ] Display screen as designed
- [ ] Create a `Invite Device` button 
- [ ] Display text **Coordinators**
- [ ] Display text **Coordinators can invite devices, edit and delete data, and manage project details.** 
- [ ] Display users own device 
- [ ] Create a `Leave Project` button 
- [ ] Display text **Participants**
- [ ] Display text **Participants can take and share observations. They cannot manage users or project details.** 
- [ ] When no participants on project, display text **No Participants have been added to this project**

# 2 
<img width="649" alt="Screen Shot 2023-11-29 at 12 40 38 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/f71c60a2-4585-4d4d-b787-94a136f25b33">

## Todo
- [ ] Display **Select Device to Invite** as header
- [ ] Display text **Not seeing a device? Make sure both devices are on the same wifi network. Make sure both devices are on the same version of Mapeo**
- [ ] Display available devices by their Device Name
- [ ] Disregad **Learn More** button
- [ ] Create a `Cancel` button 

# 3 
<img width="651" alt="Screen Shot 2023-11-29 at 12 41 35 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/e0635937-739a-425c-b712-4b190017d0c3">

## Todo
- [ ] Display **Select a Role** as header
- [ ] Display text **You are selecting a role for this device:**
- [ ] Create a `Participant` button 
- [ ] Display text **As a Participant this device can take and share observations. They cannot manage users or project details.**
- [ ] Create a `Coordinator` button 
- [ ] Display text **As a Coordinator this device can invite users, and manage project details.**

# 4 
<img width="657" alt="Screen Shot 2023-11-29 at 12 42 16 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/24fbc44c-1e5a-4ae8-b21d-8a62c0ba3afd">

## Todo
- [ ] Display **Review Invitation** as header
- [ ] Display text **You are inviting:**
- [ ] Create a `Coordinator` button 
- [ ] Create a `Send Invite` button 

# 5 

<img width="654" alt="Screen Shot 2023-11-29 at 12 42 43 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/bd43ad8e-4a72-4954-bc23-0ad8e1d8c795">

## Todo
- [ ] Display text **Waiting for device to accept invite**
- [ ] Display time invite was sent
- [ ] Create a `Cancel Invite` button 

Sabella - 👾  Dev team, this state should reflect the user waiting for someone to accept invite. So sit for 3 to 5 secs?

# 6
<img width="657" alt="Screen Shot 2023-11-29 at 12 43 23 PM" src="https://github.com/digidem/mapeo-desktop-next/assets/78557542/5139d7ae-8df9-4b74-a6d9-52af456b223e">

## Todo
- [ ] Display text **Invite Accepted**
- [ ] Display device details
- [ ] Create a `Add Another Device` button 
- [ ] If clicked `Add Another Device` button , go back to # 2
- [ ] Create a `Close` button 

- [ ] When device is invited, display device name under Particpant or Coordinator 

## Design
https://www.figma.com/file/uzynHXR0xgJu19lsCoJyXN/%F0%9F%90%9A-Shell-App?type=design&node-id=1247-153&mode=design&t=pTdIgujzMShkwaNL-0

## Copydeck
https://docs.google.com/spreadsheets/d/1l4_ImeOzXbnqsCG4BGxdH0elXFdm73e3RL_ME75wWT0/edit#gid=980984343
